version: "3.3"
services:
  edo_gazebo:
    build: ./edo_gazebo
    network_mode: host
    privileged: true
    volumes:
      - $PATH_SRC_WORKSPACE:/opt/ros_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
